title: "SMotlagh â€” Research"
description: "Research notes and updates."
url: "https://smotlagh.github.io"
baseurl: "/my-research-site"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: "G-XXXXXXX"
show_downloads: false
